Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"  # Используем образ Ubuntu 22.04
    config.vm.network "forwarded_port", guest: 80, host: 8080  # Пробрасываем порт
    
    # Указываем объем оперативной памяти и жесткого диска
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4048"  # Установите объем RAM в мегабайтах
      config.vm.disk :disk, size: "15GB", primary: true 
    end
  end